# Config for MySQL Database on local

# Default is on localhost
default: &default
  adapter: mysql2
  host: localhost
  port: 3306
  database: ecoone
  username: root
  password: Dunghoi123!@#
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5}%>
  timeout: 5000
  encoding: utf8

development:
  <<: *default
